# docker-compose.yml
version: "3.8"
services:
  # apache:
  #   container_name: apache
  #   build: ./docker/apache
  #   links:
  #     - php
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./logs/apache:/var/log/apache2
  #     - ./src/:/usr/local/apache2/htdocs/
  
  php:
    container_name: demo-backend
    build:
        context: ./src
        dockerfile: Dockerfile
    ports:
      - '8084:3000'
    command: "php artisan serve --host=0.0.0.0 --port=3000"
    volumes:
      - './src:/demo/'
    env_file:
      - './src/.env'  

  composer:
    container_name: demo-composer
    image: composer/composer
    volumes:
      - ./src/:/usr/local/apache2/htdocs/
    working_dir: /usr/local/apache2/htdocs/
    command: install    

  mysql:
    image: mysql:8.0.27
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: demo123
      MYSQL_USER: admin
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: demo-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8088:80
