
 FROM bitnami/laravel:10.2.4
 FROM php:8.2-fpm


# RUN apt-get install php8.2-openssl  

# Set the working directory in the container
WORKDIR /demo

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install additional dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libcurl4-openssl-dev \
    && docker-php-ext-install pdo_mysql zip 

RUN apt-get update
RUN apt-get install -y openssl zip unzip git curl
RUN apt-get install -y libzip-dev libonig-dev libicu-dev
RUN apt-get install -y autoconf pkg-config libssl-dev

RUN docker-php-ext-install bcmath mbstring intl opcache

# Set the file permissions for Laravel
RUN chown -R www-data:www-data /demo

# Copy the rest of the application code
COPY . .

# Generate the optimized autoloader
# RUN composer dump-autoload --optimize

RUN cat php.ini

# Generate the Laravel application key
# RUN php artisan key:generate
# RUN php artisan optimize:clear

# RUN php artisan passport:install

# Expose port 3000 for the Laravel web server
EXPOSE 3000

# Start the Laravel web server
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=3000"]
